[package]
name = "bsdiff-sys"
version = "0.1.0"
authors = ["KokaKiwi <kokakiwi@kokakiwi.net>"]
description = "Bindings to the bsdiff algorithm library."
license = "MIT"
build = "build.rs"

[dependencies]
libc = "0.2.0"

[build-dependencies]
gcc = "0.3.0"
